POST http://localhost:3000/user/create HTTP/1.1
Content-Type: application/json

{
    "name": "sample",
    "email": "teste@teste.com",
    "password": "123456",
    "role": "ROLE_USER",
    "active": "true"
}


GET http://localhost:3000/users HTTP/1.1


GET http://localhost:3000/user/1 HTTP/1.1


PUT http://localhost:3000/user/update/1 HTTP/1.1
Content-Type: application/json

{
    "name": "Sample2",
    "email": "sample@teste.com"
}
